# Generated by Django 4.1.6 on 2023-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("radius", models.CharField(max_length=200)),
                ("remote", models.CharField(max_length=200)),
                ("hybrid", models.CharField(max_length=200)),
                ("inperson", models.CharField(max_length=200)),
                ("min_salary", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=200)),
                ("job_time", models.CharField(max_length=200)),
                ("max_ed", models.CharField(max_length=200)),
                ("field_of_study", models.CharField(max_length=200)),
            ],
        ),
    ]
